CREATE TYPE user_role AS ENUM ('ADMIN', 'CLIENT', 'CASHIER');

CREATE TABLE books_categories (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name_category VARCHAR(255) NOT NULL,
                                  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       author VARCHAR(255) NOT NULL,
                       isbn VARCHAR(20) NOT NULL,
                       total_copies INTEGER NOT NULL,
                       available_copies INTEGER NOT NULL,
                       active BOOLEAN NOT NULL DEFAULT TRUE,
                       category_id BIGINT,
                       CONSTRAINT fk_books_category
                           FOREIGN KEY (category_id) REFERENCES books_categories (id)
);

CREATE TABLE clients (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL,
                         mobile_number VARCHAR(20),
                         active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE cashiers (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          mobile_number VARCHAR(20),
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          bairro VARCHAR(255),
                          cep VARCHAR(10),
                          numero VARCHAR(20),
                          complemento VARCHAR(255),
                          cidade VARCHAR(255),
                          uf VARCHAR(2)
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role user_role NOT NULL
);

CREATE TABLE loans (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       client_id BIGINT NOT NULL,
                       book_id BIGINT NOT NULL,
                       date TIMESTAMP NOT NULL,
                       active BOOLEAN NOT NULL DEFAULT TRUE,
                       CONSTRAINT fk_loans_client
                           FOREIGN KEY (client_id) REFERENCES clients (id),
                       CONSTRAINT fk_loans_book
                           FOREIGN KEY (book_id) REFERENCES books (id)
);